---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: True
    login_cmd_template: 'ssh {user}@{address} -oKexAlgorithms=diffie-hellman-group-exchange-sha1 -i {identity_file}'
    ansible_connection_options:
      ansible_ssh_common_args: '-oKexAlgorithms=diffie-hellman-group-exchange-sha1'
platforms:
  - name: cisco
provisioner:
  name: ansible
  # equivalent of settings in ansible.cfg
  config_options:
    defaults:
      ansible_buffer_read_timeout: 2
      command_timeout: 60
      stdout_callback: yaml
  inventory:
    host_vars:
      cisco:
        connection: network_cli
        ansible_network_os: community.ciscosmb.ciscosmb
        system_mode: switch
        vlans:
          - name: oneone 
            vlan_id: 11
            state: active
            shutdown: disabled
          - name: twotwo
            vlan_id: 22
            state: active
            shutdown: disabled
          - name: tritri 
            vlan_id: 33
            state: active
            shutdown: disabled
        interfaces:
          - name: GE2
            speed: 1000
            duplex: full
            enabled: True
            description: gigeth2
            mode: trunk
            vlan_tags: 1
          - name: GE3
            speed: 1000
            duplex: full
            enabled: True
            description: gigeth3
            mode: trunk
            vlan_tags: 11,22,33
        igmp:
          - vlan_id: 33
            igmp_snooping: True
            igmp_querier_version: 3
            igmp_querier_address: 192.168.100.100
      mikrotik: 
verifier:
  name: ansible