---

- name: create VLAN configuration
  cisco.ios.ios_vlans:
    config: "{{ hostvars[inventory_hostname]['vlans'] }}"

- name: configure VLANs on ports
  cli_command:
    command:
      - configure
      - "interface {{ item.name }}"
      - "switchport mode {{ item.mode }}"
      - "switchport {{ item.mode }} {{ item.mode is eq 'trunk' | ternary('allowed vlan add', 'vlan') }} {{ item.vlan_tags }} "
      - no shut
      - end
  loop: "{{ hostvars[inventory_hostname]['interfaces'] }}"