---

- name: set up interfaces
  cli_command:
    command: 
      - configure
      - "interface {{ item.name }}"
      - "speed  {{ item.speed }}"
      - "duplex {{ item.duplex }}"
      - "description {{ item.description }}"
      - "{{ item.enabled | ternary('no shutdown', 'shutdown') }}"
      - end
  loop: "{{ hostvars[inventory_hostname]['interfaces'] }}"

