---

- name: no enable eee / green-ethernet
  cli_command:
    command: "{{ item }}"
  loop:
    - configure 
    - no eee enable
    - no eee lldp enable
    - no green-ethernet energy-detect
    - end